### ISSUE TITLE
Travis build TLSV1_ALERT_INTERNAL_ERROR

### ISSUE THREAD

**Issue by B-Stefan** [neo4j/neo4j-python-driver#166] opened 2017-05-12 11:40 UTC
Since version 1.2 we got an SSL error during our unit-tests. This occurs only on the travis build environment; locally it is working. 

* [Travis-Build](https://travis-ci.org/DLR-SC/prov-db-connector/builds/231513476)
* [Project](./https://github.com/DLR-SC/prov-db-connector)

**Which versions of our products are you using?**
- Neo4j docker container version neo4j:3.1.0
**Which language (and which version of that language) are you developing with?**
- Python 3.5 
**What operating system are you on?**
- Ubuntu 12.04 or 14.04 LTS Server Edition 64 bit
**Are you working with a cluster or on a single machine?**
- Single machine 
**What code are you running?**
- Python unit test 
**What errors are you seeing?**
```
ERROR: test_horsemeat_example (examples.tests.test_examples.ExamplesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/neo4j/bolt/connection.py", line 469, in connect
    s = ssl_context.wrap_socket(s, server_hostname=host if HAS_SNI else None)
  File "/opt/python/3.5.2/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/opt/python/3.5.2/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/opt/python/3.5.2/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/python/3.5.2/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:645)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/travis/build/DLR-SC/prov-db-connector/examples/tests/test_examples.py", line 63, in test_horsemeat_example
    import examples.horsemeat_example
  File "/home/travis/build/DLR-SC/prov-db-connector/examples/horsemeat_example.py", line 22, in <module>
    prov_api = ProvDb(adapter=Neo4jAdapter, auth_info=auth_info)
  File "/home/travis/build/DLR-SC/prov-db-connector/provdbconnector/prov_db.py", line 55, in __init__
    self._adapter.connect(auth_info)
  File "/home/travis/build/DLR-SC/prov-db-connector/provdbconnector/db_adapters/neo4j/neo4jadapter.py", line 83, in connect
    self.driver = GraphDatabase.driver("bolt://{}".format(host), auth=basic_auth(user_name, user_pass))
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/neo4j/v1/api.py", line 109, in driver
    return driver_class(uri, **config)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/neo4j/v1/direct.py", line 65, in __init__
    pool.acquire()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/neo4j/v1/direct.py", line 39, in acquire
    connection = self.acquire_direct(address)  # should always be a resolved address
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/neo4j/bolt/connection.py", line 386, in acquire_direct
    connection = self.connector(address)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/neo4j/v1/direct.py", line 64, in <lambda>
    pool = DirectConnectionPool(lambda a: connect(a, security_plan.ssl_context, **config), self.address)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/neo4j/bolt/connection.py", line 474, in connect
    raise error
neo4j.exceptions.SecurityError: Failed to establish secure connection to '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:645)'
```

**What solutions have you tried already?**

* Changed the neo4 version to latest 
* Tried to run the test locally, worked  

Any idea why this error occurs only on the travis build environment?

**Comment by B-Stefan** [comment] 2017-05-15 20:21
I think this is a duplicate of https://github.com/neo4j/neo4j/issues/9233

**Comment by srbaker** [comment] 2017-05-31 08:52
Heya. Sorry you're having this trouble.

It looks like exactly the same error as https://github.com/neo4j/neo4j/issues/9233. Can you confirm the version of `libssl` in your travis environment? The current best known workaround is to install a newer `libssl`.

If this doesn't help, please let me know and I will help you further.

**Comment by B-Stefan** [comment] 2017-05-31 09:56
On Travis the openssl version is a slightly different: `OpenSSL 1.0.1f 6 Jan 2014`. 
But it is also not working. 

The workaround is not possible because there are some security restrictions. I think I have to wait for an update on the Travis environment or run all tests inside a docker container.

**Comment by srbaker** [comment] 2017-05-31 10:10
1.0.2 is the earliest version that is confirmed working, that I know of. Running your tests inside a docker container is probably the best option for now, unfortunately.

I'm going to close this issue now. Please feel free to re-open if there is something I can do to help further.

**Closed as completed by srbaker** 2017-05-31 10:10 UTC
