### ISSUE TITLE
Failed to write to closed connection with v4.2.1

### ISSUE THREAD

**Issue by yuanzhou** [neo4j/neo4j-python-driver#534] opened 2021-04-10 03:58 UTC
I'm running Neo4j 3.5.12 community version and using neo4j-python-driver v4.2.1 within a RESTful API to query against the backend Neo4j server. One issue I recently encountered is when a python script makes constant calls against the RESTful API, say over one or two hours, SOMETIMES (not always) there's one cypher query would fail with the following message:

````
[2021-04-10 02:02:33] WARNING in simple: Transaction failed and will be retried in 0.9350728883560826s (Failed to write to closed connection IPv4Address(('18.205.215.12', 7687)) (IPv4Address(('18.205.215.12', 7687))))
[2021-04-10 02:02:33] ERROR in app: Exception on /descendants/96a667104f92a38f5d4f97c38d94e738 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/neo4j/work/simple.py", line 309, in _run_transaction
    result = transaction_function(tx, *args, **kwargs)
  File "./app_neo4j_queries.py", line 920, in _execute_readonly_tx
    result = tx.run(query)
  File "/usr/local/lib/python3.6/site-packages/neo4j/work/transaction.py", line 118, in run
    result._tx_ready_run(query, parameters, **kwparameters)
  File "/usr/local/lib/python3.6/site-packages/neo4j/work/result.py", line 57, in _tx_ready_run
    self._run(query, parameters, None, None, None, **kwparameters)
  File "/usr/local/lib/python3.6/site-packages/neo4j/work/result.py", line 101, in _run
    self._attach()
  File "/usr/local/lib/python3.6/site-packages/neo4j/work/result.py", line 202, in _attach
    self._connection.fetch_message()
  File "/usr/local/lib/python3.6/site-packages/neo4j/io/_bolt3.py", line 320, in fetch_message
    details, summary_signature, summary_metadata = next(self.inbox)
  File "/usr/local/lib/python3.6/site-packages/neo4j/io/_common.py", line 79, in __next__
    tag, fields = self.pop()
  File "/usr/local/lib/python3.6/site-packages/neo4j/io/_common.py", line 73, in pop
    return next(self._messages)
  File "/usr/local/lib/python3.6/site-packages/neo4j/io/_common.py", line 63, in _yield_messages
    size, tag = unpacker.unpack_structure_header()
  File "/usr/local/lib/python3.6/site-packages/neo4j/packstream.py", line 545, in unpack_structure_header
    return self._unpack_structure_header(marker)
  File "/usr/local/lib/python3.6/site-packages/neo4j/packstream.py", line 553, in _unpack_structure_header
    raise ValueError("Expected structure, found marker %02X" % marker)
ValueError: Expected structure, found marker A0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
--
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app.py", line 1228, in get_descendants
    entity_dict = query_target_entity(id, user_token)
  File "./app.py", line 2534, in query_target_entity
    entity_dict = app_neo4j_queries.get_entity(neo4j_driver_instance, uuid)
  File "./app_neo4j_queries.py", line 71, in get_entity
    record = session.read_transaction(_execute_readonly_tx, query)
  File "/usr/local/lib/python3.6/site-packages/neo4j/work/simple.py", line 105, in __exit__
    self.close()
  File "/usr/local/lib/python3.6/site-packages/neo4j/work/simple.py", line 149, in close
    self._transaction.rollback()  # roll back the transaction if it is not closed
  File "/usr/local/lib/python3.6/site-packages/neo4j/work/transaction.py", line 157, in rollback
    self._connection.fetch_all()
  File "/usr/local/lib/python3.6/site-packages/neo4j/io/_bolt3.py", line 414, in fetch_all
    detail_delta, summary_delta = self.fetch_message()
  File "/usr/local/lib/python3.6/site-packages/neo4j/io/_bolt3.py", line 320, in fetch_message
    details, summary_signature, summary_metadata = next(self.inbox)
  File "/usr/local/lib/python3.6/site-packages/neo4j/io/_common.py", line 79, in __next__
    tag, fields = self.pop()
  File "/usr/local/lib/python3.6/site-packages/neo4j/io/_common.py", line 73, in pop
    return next(self._messages)
StopIteration
````

In this use case, the call to `/descendants/96a667104f92a38f5d4f97c38d94e738` would make a cypher query against Neo4j server and return back about 163 descendant nodes. And if I just make this call individually it always works. It only fails when the call is made by the script as one of the many calls.

At one point I started wondering if I should increase the connection lifetime when creating the driver: https://neo4j.com/docs/api/python-driver/current/api.html#max-connection-lifetime since the default is one hour. But as I said earlier, I could only reproduce this error SOMETIMES, and other times the script would run 3 hours without errors.

Please advise! I'd really appreciate if any suggestions!

**Comment by robsdedude** [comment] 2021-04-12 11:55
I'm am rather sure that the connection lifetime won't solve the issue. However, I recommend updating the neo4j server. While newer driver versions *usually* work with older server versions, we only focus on supporting the matching version plus the one before. So driver version 4.2 works best with server versions 4.2 and 4.1.  
This error looks like some sort of protocol error. Please bump the server version, enable driver logging
```
import logging
import sys

handler = logging.StreamHandler(sys.stdout)
handler.setLevel(logging.DEBUG)
logging.getLogger("neo4j").addHandler(handler)
logging.getLogger("neo4j").setLevel(logging.DEBUG)
```
then try to reproduce the issue and share the log with me.

**Comment by yuanzhou** [comment] 2021-04-12 14:26
@robsdedude thank you for the recommendation!

**Comment by yuanzhou** [comment] 2021-04-12 15:10
@robsdedude do you think it may have anything to do with the multithreading mode related to the neo4j connection pool? Because this only happened when I ran the python script within a docker container with multi-thread mode enabled from uWSGI server.  Never had this same error when I made a call against the RESTful API endpoint directly in a non-multi-threading enabled environment.

**Comment by robsdedude** [comment] 2021-04-14 08:13
I'm not sure this exact error could be caused by multithreading, but maybe, yes. Driver objects are thread safe. Sessions aren't. So you can have one driver object for the whole uWSGI application but you should open a new session for every request to your web server that needs access to the Neo4j database.

**Comment by robsdedude** [comment] 2021-07-09 20:07
I will close this issue as it has been a while. @yuanzhou, if you still have problems with this, feel free to reach out again.

**Closed as completed by robsdedude** 2021-07-09 20:07 UTC

**Comment by yuanzhou** [comment] 2021-07-12 01:32
@robsdedude thanks. I've upgraded to neo4j v4.2.5 and so far it seems to be working fine.
