### ISSUE TITLE
question regarding version 5

### ISSUE THREAD

**Issue by sander76** [neo4j/neo4j-python-driver#651] opened 2022-01-29 08:46 UTC
Hi devs.

I just started using your lib and was happy to find out you're supporting async.
I used your example as reference: https://github.com/neo4j-examples/movies-python-bolt

But soon I found out async is to be supported in v5.
Now I am in doubt whether to switch over to threading based model of wait for v5 to arrive.

So looking for a bit of advise here:
And not wanting to put any pressure on this, but could you give a clue when you expect v5 to be out ?

**Comment by robsdedude** [comment] 2022-01-31 13:50
Thanks for reaching out. 5.0 is planned to be release in summer. There is not exact release date yet. Also note that the `asyncio` support of the driver is very new. So far we've received a lot of positive feedback and it seems quite stable but while we have a lot of tests there might still be some minor bugs in the async implementation we've missed.

Personally, I'd make it dependent on what you want from the driver. If you need maximum stability, you're probably better off using threading. If you don't plan on running a service that needs the most stability possible, async should be good enough (but you'd have to wait for 5.0 to release to get a maintained driver version with async support).

I'll close the issue as it's a support request and not a bug with the driver. Please feel free to keep commenting here if you have more questions.

**Closed as completed by robsdedude** 2022-01-31 13:50 UTC
