### ISSUE TITLE
Failed to read from defunct connection Address

### ISSUE THREAD

**Issue by lingvisa** [neo4j/neo4j-python-driver#484] opened 2020-12-10 09:13 UTC
Neo4j 4.2.1
Python Bolt Driver
Mac

I am installing the latest version of Neo4j 4.2.1 and got an error message when executing a cypher through Bolt driver in Python:

`Transaction failed and will be retried in 1.0107646365462932s (Failed to read from defunct connection Address(host='localhost', port=7687) (Address(host='::1', port=7687, flow_info=0, scope_id=0)))`

The code is like this:

```
class KGLoader(object):
    def __init__(self):
        config = Configuration.get_configs()
        self.schemas = config.schemas
        self.neo4j_driver = config.get_driver()
        with self.neo4j_driver.session() as session:
            current_indexes = KGLoader.get_all_indexes(session)
            if 'NameIndex' not in current_indexes:
                session.write_transaction(lambda tx: tx.run(cypher))
                print('\nFull text NameIndex created!')
   @staticmethod
    def get_all_indexes(session):
        all_indexes = set()
        indexes = session.read_transaction(
            lambda tx:
            tx.run("CAll db.indexes"))
        for index in indexes:
            all_indexes.add(index[1])

        return all_indexes
KG_LOADER = KGLoader()
```

Also, the get_driver() method in Configuration class:

   ```
 def get_driver(self):
        try:
            return GraphDatabase.driver(self.uri, auth=(self.username, self.password), encrypted=False)
        except:
            raise ValueError("Can't connect the neo4j database. Make sure the DB is up: {} {} {}".format(self.username, self.password, self.uri))
```

The cypher is this:
`CALL db.index.fulltext.createNodeIndex('NameIndex', ['Product', 'Computer'], ['name', 'alias'])`

The same code doesn't have this problem in neo4j 4.0.4. Is the Python Bolt Driver for 4.2 not working yet? There is an issue registered here:
https://github.com/neo4j/neo4j-python-driver/issues/294

However, that issue is not exactly the same as mine.

**Comment by robsdedude** [comment] 2021-03-02 07:40
Hi @lingvisa,

does this issue still persist? I couldn't recreate the problem locally. It might be a connectivity issue.

**Comment by robsdedude** [comment] 2021-04-20 16:45
I'm closing this for now. If the issue still exists, please feel free to re-open it.

**Closed as completed by robsdedude** 2021-04-20 16:45 UTC

**Comment by ponmuthu** [comment] 2021-06-29 04:26
i am facing same issue with 4.3.1

**Comment by robsdedude** [comment] 2021-06-30 12:38
@ponmuthu could you please help me try to reproduce this error by giving me more information?
 - what server version are you using?
 - what driver version are you using?
 - what does the network topology look like? `Failed to read from defunct connection` means that at some point a connection to the server existed, but it got killed. Is there a proxy involved?
  - could you share code that causes the error?
  
  Thanks in advance.

**Comment by ponmuthu** [comment] 2021-06-30 13:26
> @ponmuthu could you please help me try to reproduce this error by giving me more information?
> 
> * what server version are you using?
> * what driver version are you using?
> * what does the network topology look like? `Failed to read from defunct connection` means that at some point a connection to the server existed, but it got killed. Is there a proxy involved?
> * could you share code that causes the error?
> 
> Thanks in advance.

server version = 4.3.1
driver = 4.3.1
Python 3.8.9 
server to connection gets (bolt://ip:7687) lost . no proxy involed here.

i will try to share code in a while.

**Comment by duclinhfetel** [comment] 2023-10-06 17:02
I get the same issue above.
neo4j python : 5.11.0
python 3.8.9
use bolt schema to connect database.

I run with Flask uwsgi + neo4j.
```neo4j.exceptions.ServiceUnavailable: Failed to read from defunct connection IPv4Address(('neo4j', 7687)) (ResolvedIPv4Address(('172.23.0.5', 7687)))```

**Comment by remort** [comment] 2023-10-16 16:39
My case with `Failed to read from defunct connection`  error was about passing a datetime Python object as one of the query parameters. Removing it or converting it to str solves the issue. It seems that something is wrong with datetime objects interpreting via `Bolt` transport. i use Memgraph. The same code with connection to Neo4j using 'neo4j://' schema was working well with datetime objects.

**Comment by robsdedude** [comment] 2023-10-16 16:48
@remort  If I had to guess, this sounds like Memgraph closing the connection because it doesn't understand the encoded temporal type or rejects it for some other reason.

**Comment by Ahmed-El-sayed-Mahmoud** [comment] 2024-12-05 15:23
I have same issue , when I do lots of queries 7:18:01.261 | ERROR   | datax.presentation.middlewares.error_handling_middleware - Exception in middleware: ValueError - Error executing query: Failed to read from defunct connection IPv4Address((******)) (ResolvedIPv4Address(('*****)))
Traceback (most recent call last):
  File "F:\datax-backend_\.venv\Lib\site-packages\anyio\streams\memory.py", line 111, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\.venv\Lib\site-packages\anyio\streams\memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\datax-backend_\.venv\Lib\site-packages\anyio\streams\memory.py", line 124, in receive
    return receiver.item
           ^^^^^^^^^^^^^
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\.venv\Lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\datax-backend_\datax\presentation\middlewares\error_handling_middleware.py", line 27, in error_handling_middleware
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "F:\datax-backend_\.venv\Lib\site-packages\sentry_sdk\integrations\starlette.py", line 200, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\middleware\base.py", line 189, in __call__
    with collapse_excgroups():
         ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\_utils.py", line 93, in collapse_excgroups
    raise exc
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\middleware\base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\datax\presentation\middlewares\request_logger_middleware.py", line 34, in request_logger_middleware
    raise e
  File "F:\datax-backend_\datax\presentation\middlewares\request_logger_middleware.py", line 28, in request_logger_middleware
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "F:\datax-backend_\.venv\Lib\site-packages\sentry_sdk\integrations\starlette.py", line 200, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\middleware\base.py", line 189, in __call__
    with collapse_excgroups():
         ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\_utils.py", line 93, in collapse_excgroups
    raise exc
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\middleware\base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\datax\presentation\middlewares\authentication_middleware.py", line 97, in authentication_middleware
    raise e
  File "F:\datax-backend_\datax\presentation\middlewares\authentication_middleware.py", line 75, in authentication_middleware
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "F:\datax-backend_\.venv\Lib\site-packages\sentry_sdk\integrations\starlette.py", line 200, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\.venv\Lib\site-packages\opentelemetry\instrumentation\asgi\__init__.py", line 731, in __call__
    await self.app(scope, otel_receive, otel_send)
  File "F:\datax-backend_\.venv\Lib\site-packages\sentry_sdk\integrations\starlette.py", line 298, in _sentry_exceptionmiddleware_call
    await old_call(self, scope, receive, send)
  File "F:\datax-backend_\.venv\Lib\site-packages\sentry_sdk\integrations\starlette.py", line 200, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "F:\datax-backend_\.venv\Lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\.venv\Lib\site-packages\sentry_sdk\integrations\fastapi.py", line 143, in _sentry_app
    return await old_app(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\.venv\Lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\.venv\Lib\site-packages\logfire\_internal\integrations\fastapi.py", line 129, in patched_run_endpoint_function
    return await instrumentation.run_endpoint_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\.venv\Lib\site-packages\logfire\_internal\integrations\fastapi.py", line 254, in run_endpoint_function
    return await original_run_endpoint_function(dependant=dependant, values=values, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\.venv\Lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\.venv\Lib\site-packages\dependency_needle\container\container.py", line 238, in wrapper
    result = await fn(*args, **built_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\datax\presentation\controllers\graph_db_endpoints\graphdb.py", line 15, in query_endpoint
    result = await graphdb_query_data_viewer.do_operation(graphdb_query_input.to_app())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax-backend_\datax\application\blocks\data_viewer\graph_data_viewer\graphdb_query_data_viewer\graphdb_query.py", line 171, in do_operation

**Comment by Ahmed-El-sayed-Mahmoud** [comment] 2024-12-05 15:26
I am using 
neo4j = "^5.27.0"
system -> windows 10
python = ">=3.11,<3.13"

**Comment by robsdedude** [comment] 2024-12-09 15:06
Does the same error occur when using `asyncio` instead of `anyio`? The driver has not been developed against or tested with any other async runtime but `asyncio`.

Also, could you please format the stack trace using
```
a
code block
for better readability
```
:bow: 
Finally, I think you've truncated the stack trace. Can you make sure it's complete? That fact that 'neo4j' isn't in the stack trace even once indicates that either it has been truncated, or this is not a driver issue.
