### ISSUE TITLE
ClientError: {code: Neo.ClientError.Transaction.TransactionTimedOut} 

### ISSUE THREAD

**Issue by williamdarkocode** [neo4j/neo4j-python-driver#633] opened 2021-12-21 07:39 UTC
My code:

```py
match_query = """
UNWIND $edges AS edge
MATCH (source: Paper {pid: edge.s})
MATCH (target: Paper {pid: edge.t})
MERGE (source)-[:CITES]->(target)
"""

def match_nodes(tx, itms):
  tx.run(match_query, edges=itms)

edges = []
with driver.session() as session:
  for e in edge_list:
    edges.append({'s': e[0], 't': e[1]})
    if len(edges) % 5000 == 0:
      session.run(match_nodes, edges)
      edges = []
  session.run(match_nodes, edges)
```
The error message:

```
{code: Neo.ClientError.Transaction.TransactionTimedOut} {message: The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. The transaction has not completed within the specified timeout (dbms.transaction.timeout). You may want to retry with a longer timeout. }
```

Can someone please please, help. How do I change the transaction timeout? I'm using a free sandbox, and I need to get this done soon! 

Thanks!

**Comment by robsdedude** [comment] 2021-12-21 13:43
Hi and thanks for getting in touch.

When you say "free sandbox", do you refer to our sandboxes available here: https://sandbox.neo4j.com/ ? If so, I'm not 100% sure, but I wouldn't be surprised if they had a transaction timeout configured. They are merely meant for a little manual tinkering and getting familiar with Neo4j. You could give Aura free (our free cloud service) as try https://neo4j.com/cloud/aura/ and see if that resolves your issue.

**Comment by robsdedude** [comment] 2021-12-23 09:12
I'll close this issue as it's not a bug in the driver. Feel free to comment on it still, if there are open question you think I can help you with.

**Closed as completed by robsdedude** 2021-12-23 09:12 UTC
