### ISSUE TITLE
Add support for asyncio

### ISSUE THREAD

**Issue by savv** [neo4j/neo4j-python-driver#180] opened 2017-09-11 17:33 UTC
Are there any plans to add async versions of this API?

I.e. is there/will there be a way to await on neo4j queries?

**Comment by technige** [comment] 2017-09-15 08:50
There are no plans to add this for Python in the near future. One of the reasons is due to the complexity around supporting both Python 2.x and 3.x in the same driver, given that async functionality is Python 3 only.

**Comment by adamrothman** [comment] 2017-09-23 00:08
@savvopoulos Right now the best solution is to execute blocking calls to Neo4j using the event loop's [`run_in_executor`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.run_in_executor) method. Something like this:

```python
import asyncio

from neo4j.v1 import GraphDatabase


class AsyncNeo4j:

    _driver = None

    @classmethod
    def get_driver(cls):
        if cls._driver is None:
            cls._driver = GraphDatabase.driver('bolt://my-neo4j-host:7687')
        return cls._driver

    @classmethod
    async def run(cls, statement, *args, **kwargs):
        """Run a statement asynchronously using the event loop's default thread
        pool executor.
        """
        driver = cls.get_driver()

        def run():
            with driver.session() as session:
                result = session.run(statement, *args, **kwargs)
            return result

        loop = asyncio.get_event_loop()
        # Passing None uses the default executor
        return await loop.run_in_executor(None, run)
```

This works well enough – I use it in production – but it's obviously not ideal.

@technige It would be truly outstanding if one day the code responsible for managing the Neo4j _protocol_ (packing queries and parameters for Bolt transport, unpacking the responses, etc.) could be separated from the _transport_ (currently, blocking socket I/O) code.

This is precisely what [Hyper-h2](http://python-hyper.org/h2/) does for HTTP/2. It provides a full implementation of the protocol without any I/O whatsoever. This makes it easy for third parties to wrap the protocol and supply their own I/O, whether via an [`asyncio.Protocol`](https://docs.python.org/3/library/asyncio-protocol.html#protocols), the equivalent Twisted construct, or even some alternative synchronous transport.

I would definitely be interested in writing such a wrapper, given an appropriate protocol implementation. What do you think?

**Comment by PaulRudin** [comment] 2017-11-18 08:06
For example, the python elasticsearch  client has an adapter with a different transport for use with asycio: https://github.com/elastic/elasticsearch-py-async

**Comment by davebshow** [comment] 2017-12-11 19:35
I've been evaluating the potential for async Python connections to Neo4j, and ended up implementing a Bolt client/server for `asyncio`. Pretty simple, more of a POC at this point, but I think it would be cool if community members picked up the project: https://github.com/davebshow/asyncbolt

Also, @adamrothman, the `asycbolt.messaging` and `asyncbolt.buffer` modules should be able to be used to pack and unpack Bolt messages independently of the `asyncio.Protocol` implementation. Any other implementation of the protocol that used them would have to implement all of the session details etc., but the structs and enums are all defined in `asyncbolt.messaging`, and the buffers appear to be working, though not very well tested or optimized.

**Comment by savv** [comment] 2018-03-19 14:33
@adamrothman That's a start, but aren't you blocking while results are being fetched? I don't think the `session.run()`, which you run inside of `run_in_executor`, fetches the results. So, each time you iterate over the `BoltStatementResult` iterator returned by `AsyncNeo4j.run()`, your entire server will block while a row is being fetched.

**Comment by savv** [comment] 2018-03-19 16:42
This worked well for me:
```
    async def arun(self, query):
        with self.driver.session(access_mode=neo4j.v1.READ_ACCESS) as session:
            def run():
                return session.run(query).records()
            it = await self.loop.run_in_executor(self.executor, run)

            def iterate():
                try:
                    return next(it)
                except StopIteration:
                    return None
            while True:
                res = await self.loop.run_in_executor(self.executor, iterate)
                if res is None:
                    return
                else:
                    yield res
```

**Comment by adamrothman** [comment] 2018-03-19 19:47
Ah, I didn't realize it was fetching results lazily – thanks for the tip @savvopoulos. Maybe something like this would be simpler?

```python
@classmethod
async def run(cls, statement, *args, **kwargs):
    """Run a statement asynchronously using the event loop's default thread
    pool executor.
    """
    driver = cls.get_driver()

    def run():
        with driver.session() as session:
            result = session.run(statement, *args, **kwargs)
        return list(result.records())

    loop = asyncio.get_event_loop()
    # Passing None uses the default executor
    return await loop.run_in_executor(None, run)
```

Just consume all the records on the thread and return them in a list?

**Comment by savv** [comment] 2018-03-19 20:58
For smaller datasets this is fine, otherwise you consume a lot of memory.

(By the way, still not a 100% sure if they are fetched lazily; but a few tests seem to suggest so.)

**Comment by technige** [comment] 2018-04-05 11:01
Yes, results are fetched lazily.

**Comment by savv** [comment] 2018-04-10 10:49
Here's the complete class, including retry logic, in case the connection is lost. I've been using this successfully for a while now.

```
from concurrent import futures
import neo4j
from neo4j.v1 import GraphDatabase, basic_auth, Node
import time
import traceback

RETRY_WAITS = [0, 1, 4]  # How long to wait after each successive failure.
class Neo4j:
    """Neo4j database API."""
    def __init__(self, config, loop):
        self.config = config
        self.loop = loop
        self.executor = futures.ThreadPoolExecutor(max_workers=30)
        for retry_wait in RETRY_WAITS:
            try:
                self.init_driver()
                break
            except:
                if retry_wait == RETRY_WAITS[-1]:
                    raise
                else:
                    print('WARNING: retrying to Init DB; err:')
                    traceback.print_exc()
                    time.sleep(retry_wait)  # wait for 0, 1, 3... seconds.

    def init_driver(self):
        auth = basic_auth(self.config['user'], self.config['pass'])
        self.driver = GraphDatabase.driver(self.config['url'], auth=auth)

    async def afetch_start(self, query):
        session = self.driver.session(access_mode=neo4j.v1.READ_ACCESS)
        def run():
            return session.run(query).records()
        return session, await self.loop.run_in_executor(self.executor, run)

    async def afetch_iterate(self, session, iter):
            def iterate():
                try:
                    return next(iter)
                except StopIteration:
                    return None
            while True:
                res = await self.loop.run_in_executor(self.executor, iterate)
                if res is None:
                    return
                else:
                    yield dict(res)

    async def afetch(self, query):
        for retry_wait in RETRY_WAITS:
            try:
                session, iter = await self.afetch_start(query)
                break
            except (BrokenPipeError, neo4j.exceptions.ServiceUnavailable) as e:
                if retry_wait == RETRY_WAITS[-1]:
                    raise
                else:
                    await asyncio.sleep(retry_wait)
                    await self.loop.run_in_executor(self.executor, self.init_driver)
        async for x in self.afetch_iterate(session, iter):
            yield x

        await self.loop.run_in_executor(self.executor, session.close)


    async def afetch_one(self, query):
        async for i in self.afetch(query):
            return i
        return None

    async def aexec(self, query):
        async for i in self.afetch(query):
            pass
        return
```

**Comment by technige** [comment] 2018-04-10 12:33
I'd be happy to look at how we might introduce async to Python if there's enough interest. Let's collect :+1:s on this comment...

**Comment by g3rd** [comment] 2018-04-27 01:41
@savvopoulos Thanks for the example!
1. First off, thanks for protecting against the `BrokenPipeError` exception. I see that exception a lot throughout my environments.
2. I don't see where the sessions or db connection being closed. Is that by design?

Edit:
RE: 2 - Found the `close()`

**Comment by technige** [comment] 2018-05-10 09:12
As the plan currently stands, we will likely remove support for Python 2 when the 2.0 series drivers are released (probably next year, in conjunction with the 4.0 server release although timescales are still very fluid).

After Python 2 had been removed from the equation, we will look at adding async support.

**Comment by technige** [comment] 2018-08-22 09:41
Adding support for asyncio is now on our roadmap. Due to other priorites however, this will arrive _at the earliest_ in the second half of 2019, but may not arrive until later. Note that support for Python 2 will be dropped in the first half of 2019, paving the way for this feature.

Closing this issue now that the item has been added to the roadmap.

**Closed as completed by technige** 2018-08-22 09:41 UTC
Labels: feature request

**Comment by technige** [comment] 2018-11-20 09:29
![](https://github.trello.services/images/mini-trello-icon.png) [Python Driver: drop support for Python 2](https://trello.com/c/j8YvoLHZ/278-python-driver-drop-support-for-python-2)

**Comment by mjmare** [comment] 2019-10-06 19:54
Any news on asyncio support?

**Comment by timkofu** [comment] 2020-08-11 10:18
Being that that Python 2.7 is now no-longer supported by the PSF itself, will the next release Python3 only and async?

**Comment by timkofu** [comment] 2020-09-03 10:06
Our current setup is to use the [HTTP API](https://neo4j.com/docs/http-api/current/introduction/) with [httpx](https://github.com/encode/httpx).

This works perfectly for us; it makes the model-layer design utterly flexible and is blazing fast on Neo4j 4.1.1.

**Comment by psuresh39** [comment] 2020-12-13 08:42
is this happening? :)

**Comment by jiaola** [comment] 2020-12-16 12:49
Any updates?

**Comment by havardthom** [comment] 2021-02-04 08:30
Any update on asyncio support? Where exactly on the roadmap is this feature? is the roadmap public?

**Comment by o1o1o3** [comment] 2021-03-08 23:25
Need this

**Comment by DachuanZhao** [comment] 2021-03-29 06:31
Any processing ?

**Comment by vijay-saadhvi** [comment] 2021-04-02 22:55
@technige Any updates on this?

**Comment by havardthom** [comment] 2021-05-07 20:11
Update from neo4j discord

![image](https://user-images.githubusercontent.com/34199185/117503257-fc63b680-af80-11eb-9573-71670f0bab57.png)

**Comment by jamesba** [comment] 2021-05-10 10:20
In one of our projects we've written our own internal asyncio wrapper around the synchronous driver (using `run_in_executor` to run the synchronous code on a separate thread. This approach isn't as good as a "native" asyncio implementation, of course, but works fairly well for most purposes we've found. It's possible that if there's demand we could share our code for that.

**Comment by AndreaCensi** [comment] 2021-05-18 11:03
@jamesba It would be nice to see the code. 

(to the developers: I think most Python backend projects as of now use `asyncio`, and without an `asyncio` version, it's hard to make a case for `neo4j`)

**Comment by havardthom** [comment] 2021-09-13 08:47
@jamesba Would love to see your workaround for this issue. 

That goes for all participants in this thread, feel free to share your approaches to run the driver asynchronously.

I also think this issue should be reopened to make it easier for people to voice their support for this issue. IMO web development in Python is obviously moving in the async direction and we need to show neo4j that this driver should too.

**Comment by j616** [comment] 2021-09-17 09:17
Hello. I work alongside @jamesba . We've factored out our async wrapper into its own library but need to go through our internal process to open-source it. That jobs on the backlog but might be a couple of weeks off. We've got quite a bit on atm. But it is coming!

**Comment by jamesba** [comment] 2021-10-19 12:54
https://pypi.org/project/aiocypher/ and https://github.com/bbc/rd-cloudfit-python-aiocypher may be of interest.

(It took a while to get permission)

**Comment by robsdedude** [comment] 2022-01-03 11:06
So here we finally are: experimental, native async support :tada:

I'll copy-paste the release note here as well.

> Happy New Year! :confetti_ball:
> 
> The Python driver version 5.0.0a1 with `asyncio` support has been released!
> 
> This pre-release does not contain any 5.0 features and future pre-releases might have to be API-breaking. This release' sole purpose it to give early access to the async driver.
> 
> [https://pypi.org/project/neo4j/5.0.0a1/](https://pypi.org/project/neo4j/5.0.0a1/)
>  
> Find the changelog here: [https://github.com/neo4j/neo4j-python-driver/wiki](https://github.com/neo4j/neo4j-python-driver/wiki)
> 
> We are very happy for any feedback on this feature.

**Comment by mjmare** [comment] 2022-01-03 11:23
That's a nice new year's gift! Thanks for the hard work.

**Comment by havardthom** [comment] 2022-01-11 15:06
> So here we finally are: experimental, native async support 🎉
> 
> I'll copy-paste the release note here as well.
> 
> > Happy New Year! 🎊
> > The Python driver version 5.0.0a1 with `asyncio` support has been released!
> > This pre-release does not contain any 5.0 features and future pre-releases might have to be API-breaking. This release' sole purpose it to give early access to the async driver.
> > https://pypi.org/project/neo4j/5.0.0a1/
> > Find the changelog here: https://github.com/neo4j/neo4j-python-driver/wiki
> > We are very happy for any feedback on this feature.

This looks great, thank you! Did an experimental migration to v5.0.0a1 in our project and got all our tests passing, no issues so far. Will of course wait for a stable release before we switch over.

**Comment by technige** [comment] 2022-02-01 15:32
Awesome work @robsdedude :)
