### ISSUE TITLE
Rolling back transaction leads to AttributeError

### ISSUE THREAD

**Issue by istrel** [neo4j/neo4j-python-driver#266] opened 2018-10-28 19:18 UTC
Prerequisites:
- we have 3 servers (one follower, two leaders) behind DNS
- Neo4J address configured this way: 'bolt+routing://private_domain:7687'

When we shutdown leader, we start facing such stack traces (`...` replaced parts of stack in our code);
```
OSError: [Errno 113] No route to host
  ...
  File "/code/db/neo4j.py", line 22, in read_transaction
    return self.session.read_transaction(*args, **kwargs)
  File "neo4j/__init__.py", line 697, in read_transaction
    return self._run_transaction(READ_ACCESS, unit_of_work, *args, **kwargs)
  File "neo4j/__init__.py", line 664, in _run_transaction
    self._open_transaction(access_mode, metadata, timeout)
  File "neo4j/__init__.py", line 610, in _open_transaction
    self._connect(access_mode)
  File "neo4j/__init__.py", line 367, in _connect
    self._connection = self._acquirer(access_mode)
  File "neobolt/routing.py", line 425, in acquire
    connection = self.acquire_direct(address)  # should always be a resolved address
  File "neobolt/direct.py", line 575, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "neo4j/__init__.py", line 255, in connector
    return connect(address, **dict(config, **kwargs))
  File "neobolt/direct.py", line 937, in connect
    raise last_error
  File "neobolt/direct.py", line 927, in connect
    s = _connect(resolved_address, **config)
  File "neobolt/direct.py", line 793, in _connect
    s.connect(resolved_address)
AttributeError: 'NoneType' object has no attribute 'rollback'
  ...
  File "neo4j/__init__.py", line 358, in __exit__
    self.close()
  File "neo4j/__init__.py", line 391, in close
    self.rollback_transaction()
  File "neo4j/__init__.py", line 643, in rollback_transaction
    self._connection.rollback(on_success=metadata.update)
```

Here is some logs from neobolt logger captured immediately before exception:
```
01:28:56 [#B50A]  C: RESET
01:28:56 [#B50A]  S: IGNORED
01:28:56 [#B50A]  S: SUCCESS {}
01:28:57 [#0000]  C: <RESOLVE> Address(host='10.230.195.3', port=7687)
01:28:57 [#0000]  C: <OPEN> ('10.230.195.3', 7687)
01:29:00 [#0000]  C: <ERROR> OSError 113 'No route to host'
01:29:00 [#0000]  C: <CLOSE> ('10.230.195.3', 7687)
```

Python libraries:
neo4j==1.7.0
neobolt==1.7.0

Neo4j version: 3.4.7

**Comment by technige** [comment] 2018-10-29 10:00
Thanks for reporting. This looks like a bug.

**Comment by technige** [comment] 2018-10-29 15:49
@istrel Do you have any sample code that could help us reproduce the error?

**Comment by istrel** [comment] 2018-10-30 17:19
@technige I've reduced to this sample script

```
import os
from neo4j.v1 import GraphDatabase, basic_auth

neo4j_addr = os.getenv("NEO4J_ADDR", "bolt+routing://<host>:7687")
neo4j_password = os.getenv("NEO4J_PASSWORD", "neo4j")

driver = GraphDatabase.driver(
    neo4j_addr,
    auth=basic_auth("neo4j", neo4j_password),
)


def do_iteration():
    with driver.session() as session:
        def increment_counter(tx):
            tx.run("""
                MERGE
                    (t:TestNode)
                ON CREATE SET
                    t.counter = 0
                SET
                    t.counter = t.counter + 1
            """, {})

        session.write_transaction(increment_counter)


for i in range(100000):
    print(i)
    do_iteration()
```

When I shut down leader I see the following:
```
...
500
501
Traceback (most recent call last):
  File "test.py", line 25, in do_iteration
    session.write_transaction(increment_counter)
  File "/usr/local/lib/python3.6/site-packages/neo4j/__init__.py", line 701, in write_transaction
    return self._run_transaction(WRITE_ACCESS, unit_of_work, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/neo4j/__init__.py", line 664, in _run_transaction
    self._open_transaction(access_mode, metadata, timeout)
  File "/usr/local/lib/python3.6/site-packages/neo4j/__init__.py", line 610, in _open_transaction
    self._connect(access_mode)
  File "/usr/local/lib/python3.6/site-packages/neo4j/__init__.py", line 367, in _connect
    self._connection = self._acquirer(access_mode)
  File "/usr/local/lib/python3.6/site-packages/neobolt/routing.py", line 425, in acquire
    connection = self.acquire_direct(address)  # should always be a resolved address
  File "/usr/local/lib/python3.6/site-packages/neobolt/direct.py", line 575, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/usr/local/lib/python3.6/site-packages/neo4j/__init__.py", line 255, in connector
    return connect(address, **dict(config, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/neobolt/direct.py", line 937, in connect
    raise last_error
  File "/usr/local/lib/python3.6/site-packages/neobolt/direct.py", line 927, in connect
    s = _connect(resolved_address, **config)
  File "/usr/local/lib/python3.6/site-packages/neobolt/direct.py", line 793, in _connect
    s.connect(resolved_address)
OSError: [Errno 51] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 30, in <module>
    do_iteration()
  File "test.py", line 25, in do_iteration
    session.write_transaction(increment_counter)
  File "/usr/local/lib/python3.6/site-packages/neo4j/__init__.py", line 358, in __exit__
    self.close()
  File "/usr/local/lib/python3.6/site-packages/neo4j/__init__.py", line 391, in close
    self.rollback_transaction()
  File "/usr/local/lib/python3.6/site-packages/neo4j/__init__.py", line 643, in rollback_transaction
    self._connection.rollback(on_success=metadata.update)
AttributeError: 'NoneType' object has no attribute 'rollback'
```

**Comment by technige** [comment] 2018-11-01 15:31
Fixed by https://github.com/neo4j/neo4j-python-driver/pull/271

**Closed as completed by technige** 2018-11-01 15:31 UTC
Labels: bug

**Comment by istrel** [comment] 2018-11-07 13:12
Tested 1.7.1 - it works! 🎉 

Thank you very much!

**Comment by mhelal** [comment] 2020-09-10 15:42
Hi

I did not understand how it was fixed and what to do to recover from this error. Can you please explain more.

I am getting null connection trying to connect from neomodel for Django (https://pypi.org/project/django_neomodel/):

 $ python3 manage.py install_labels
Setting up indexes and constraints...

Found django_neomodel.DjangoNode
 ! Skipping class django_neomodel.DjangoNode is abstract
Found qApp.models.Surah
 + Creating unique constraint for title on label Surah for class qApp.models.Surah
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/manal/Sites/q_venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/manal/Sites/q_venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/manal/Sites/q_venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/manal/Sites/q_venv/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/Users/manal/Sites/q_venv/lib/python3.8/site-packages/django_neomodel/management/commands/install_labels.py", line 12, in handle
    install_all_labels(stdout=self.stdout)
  File "/Users/manal/Sites/q_venv/lib/python3.8/site-packages/neomodel/core.py", line 70, in install_all_labels
    install_labels(cls, quiet=False, stdout=stdout)
  File "/Users/manal/Sites/q_venv/lib/python3.8/site-packages/neomodel/core.py", line 45, in install_labels
    db.cypher_query("CREATE CONSTRAINT "
  File "/Users/manal/Sites/q_venv/lib/python3.8/site-packages/neomodel/util.py", line 27, in wrapper
    self.set_connection(config.DATABASE_URL)
  File "/Users/manal/Sites/q_venv/lib/python3.8/site-packages/neomodel/util.py", line 58, in set_connection
    self.driver = GraphDatabase.driver('bolt://' + hostname,
  File "/Users/manal/Sites/q_venv/lib/python3.8/site-packages/neo4j/v1/api.py", line 94, in driver
    return Driver(uri, **config)
  File "/Users/manal/Sites/q_venv/lib/python3.8/site-packages/neo4j/v1/api.py", line 133, in __new__
    return subclass(uri, **config)
  File "/Users/manal/Sites/q_venv/lib/python3.8/site-packages/neo4j/v1/direct.py", line 73, in __new__
    pool.release(pool.acquire())
  File "/Users/manal/Sites/q_venv/lib/python3.8/site-packages/neo4j/v1/direct.py", line 44, in acquire
    return self.acquire_direct(self.address)
  File "/Users/manal/Sites/q_venv/lib/python3.8/site-packages/neo4j/bolt/connection.py", line 455, in acquire_direct
    connection.pool = self
AttributeError: 'NoneType' object has no attribute 'pool'


Thank you
