### ISSUE TITLE
Asyncio support

### ISSUE THREAD

**Issue by mjmare** [neo4j/neo4j-python-driver#272] opened 2018-11-10 12:10 UTC
It would be nice to have async support in the Neo4j python driver.

**Comment by technige** [comment] 2018-11-12 10:17
Duplicate of https://github.com/neo4j/neo4j-python-driver/issues/180 - this has already been added to our roadmap.

**Closed as completed by technige** 2018-11-12 10:17 UTC

**Comment by technige** [comment] 2018-11-20 09:28
![](https://github.trello.services/images/mini-trello-icon.png) [Python Driver: drop support for Python 2](https://trello.com/c/j8YvoLHZ/278-python-driver-drop-support-for-python-2)
